name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Print current directory
        run: pwd

      - name: List files in root directory
        run: ls -la

      - name: List files in appointments-api directory
        run: ls -la
        working-directory: appointments-api

      - name: Install dependencies
        run: npm install
        working-directory: appointments-api # Certifique-se de que os comandos estão sendo executados no diretório correto

      - name: Run tests
        run: npm test
        working-directory: appointments-api # Certifique-se de que os comandos estão sendo executados no diretório correto

      - name: Collect coverage
        run: npm run test -- --coverage
        working-directory: appointments-api # Certifique-se de que os comandos estão sendo executados no diretório correto
